---
name: CI
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  test:
    runs-on: macos-latest
    name: Test
    steps:
      - uses: actions/checkout@v2
      - name: Start minikube
        run: |
          ./setup.sh
